-- Table: public.cliente

-- DROP TABLE IF EXISTS public.cliente;

CREATE TABLE IF NOT EXISTS public.cliente
(
    estado smallint,
    codigo_cliente bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    edad bigint,
    direccion character varying(255) COLLATE pg_catalog."default",
    genero character varying(255) COLLATE pg_catalog."default",
    identificacion character varying(255) COLLATE pg_catalog."default",
    nombre character varying(255) COLLATE pg_catalog."default",
    password character varying(255) COLLATE pg_catalog."default",
    telefono character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT cliente_pkey PRIMARY KEY (codigo_cliente),
    CONSTRAINT cliente_estado_check CHECK (estado >= 0 AND estado <= 1)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.cliente
    OWNER to postgres;
	
-- Table: public.cuenta

-- DROP TABLE IF EXISTS public.cuenta;

CREATE TABLE IF NOT EXISTS public.cuenta
(
    estado smallint,
    saldo_actual real,
    saldo_inicial real,
    tipo_cuenta smallint,
    cliente bigint,
    codigo_cuenta bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    numero_cuenta character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT cuenta_pkey PRIMARY KEY (codigo_cuenta),
    CONSTRAINT cuenta_estado_check CHECK (estado >= 0 AND estado <= 1),
    CONSTRAINT cuenta_tipo_cuenta_check CHECK (tipo_cuenta >= 0 AND tipo_cuenta <= 1)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.cuenta
    OWNER to postgres;
	
-- Table: public.movimiento

-- DROP TABLE IF EXISTS public.movimiento;

CREATE TABLE IF NOT EXISTS public.movimiento
(
    saldo real,
    tipo_movimiento smallint,
    valor real,
    codigo_cuenta bigint,
    codigo_movimiento bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    fecha timestamp(6) without time zone,
    CONSTRAINT movimiento_pkey PRIMARY KEY (codigo_movimiento),
    CONSTRAINT fkqin0sroqcpjr406x32t419ys4 FOREIGN KEY (codigo_cuenta)
        REFERENCES public.cuenta (codigo_cuenta) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT movimiento_tipo_movimiento_check CHECK (tipo_movimiento >= 0 AND tipo_movimiento <= 1)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.movimiento
    OWNER to postgres;


INSERT INTO public.cliente (estado, edad, direccion, genero, identificacion, nombre, password, telefono, codigo_cliente) 
VALUES (0, 25, 'Otavalo sn y principal', 'Masculino', 'ID123456', 'Jose Lema', '1234', '098254785',1);

INSERT INTO public.cliente (estado, edad, direccion, genero, identificacion, nombre, password, telefono, codigo_cliente) 
VALUES (0, 32, 'Amazonas y NNUU', 'Femenino', 'ID654321', 'Marianela Montalvo', '5678', '097548965',2);

INSERT INTO public.cliente (estado, edad, direccion, genero, identificacion, nombre, password, telefono, codigo_cliente) 
VALUES (0, 40, '13 junio y Equinoccial', 'Masculino', 'ID987654', 'Juan Osorio', '1245', '098874587',3);



INSERT INTO public.cuenta (estado, saldo_actual, saldo_inicial, tipo_cuenta, cliente, numero_cuenta, codigo_cuenta) 
VALUES (0, 2000.00, 2000.00, 0, 1, '478758', 1 );

INSERT INTO public.cuenta (estado, saldo_actual, saldo_inicial, tipo_cuenta, cliente, numero_cuenta, codigo_cuenta) 
VALUES (0, 100.00, 100.00, 1, 2, '225487', 2 );

INSERT INTO public.cuenta (estado, saldo_actual, saldo_inicial, tipo_cuenta, cliente, numero_cuenta, codigo_cuenta) 
VALUES (0, 0.00, 0.00, 0, 3, '495878', 3 );

INSERT INTO public.cuenta (estado, saldo_actual, saldo_inicial, tipo_cuenta, cliente, numero_cuenta, codigo_cuenta) 
VALUES (0, 540.00, 540.00, 0, 2, '496825', 4 );




INSERT INTO public.movimiento (saldo, tipo_movimiento, valor, codigo_cuenta, fecha) 
VALUES (1425.00, 1, 2000.00, 1, '2025-04-01 10:30:00');

INSERT INTO public.movimiento (saldo, tipo_movimiento, valor, codigo_cuenta, fecha) 
VALUES (700.00, 0, 100.00, 2, '2025-04-02 10:30:00');

INSERT INTO public.movimiento (saldo, tipo_movimiento, valor, codigo_cuenta, fecha) 
VALUES (150.00, 0, 150.00, 3, '2025-04-03 10:30:00');

INSERT INTO public.movimiento (saldo, tipo_movimiento, valor, codigo_cuenta, fecha) 
VALUES (0.00, 1, 540.00, 4, '2025-04-04 10:30:00');

