server:
  port: 8090

spring:
  application:
    name: msvc-cliente

  datasource:
    url: jdbc:postgresql://localhost:5433/bancadb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: postgresql

  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka